-- Script generated by Redgate Compare v1.14.1.10156


-- deployment: Dropping staff.address2...
ALTER TABLE staff DROP COLUMN address2;


-- deployment: Dropping staff.address1...
ALTER TABLE staff DROP COLUMN address1;

