-- Script generated by Redgate Compare v1.14.1.10156


-- deployment: Dropping get_employees...
DROP PROCEDURE get_employees;


-- deployment: Creating get_employees...
CREATE PROCEDURE get_employees ()
BEGIN
select * from employees;
END;

