-- Script generated by Redgate Compare v1.14.1.10156


-- deployment: Creating staff...
CREATE TABLE staff (
    staff_no int NOT NULL,
    birth_date date NOT NULL,
    first_name varchar(14) NOT NULL,
    last_name varchar(16) NOT NULL,
    gender enum('M','F') NOT NULL,
    hire_date date NOT NULL,
    middle_name varchar(45) NULL
);
ALTER TABLE staff ADD PRIMARY KEY (staff_no);

