-- Script generated by Redgate Compare v1.14.1.10156


-- deployment: Creating staff.address2...
ALTER TABLE staff ADD COLUMN address2 varchar(45) NULL;


-- deployment: Creating staff.address1...
ALTER TABLE staff ADD COLUMN address1 varchar(45) NULL;

